name: CI

on:
  push:
  pull_request:

jobs:
  test-invalid-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./release-tag-to-version
        id: invalid
        continue-on-error: true
        with:
          release-tag: not-a-tag

      - name: assert invalid tag fails
        run: test "${{ steps.invalid.outcome }}" = "failure"

  test-assert-version-match:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./assert-version
        with:
          filename: fixtures/assert-version/binary.sh
          expected-version: "1.2.3"

  test-assert-version-mismatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./assert-version
        id: mismatch
        continue-on-error: true
        with:
          filename: fixtures/assert-version/binary.sh
          expected-version: "3.2.1"

      - name: assert mismatch fails
        run: test "${{ steps.mismatch.outcome }}" = "failure"

  test-assert-version-invalid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./assert-version
        id: invalid
        continue-on-error: true
        with:
          filename: fixtures/assert-version/binary.sh
          expected-version: "not-a-version"

      - name: assert invalid version fails
        run: test "${{ steps.invalid.outcome }}" = "failure"
